package:
  format-version: "1.0.0"
  name: "reference_apps_pic32cm"
  type: "application"
  status: "production"
  required: false
  version: "1.0.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.20.0"
    - name: "core"
      type: "package"
      version: "v3.14.1"
    - name: "bsp"
      type: "package"
      version: "3.21.1"
    - name: "gfx"
      type: "package"
      version: "3.15.3"
    - name: "touch"
      type: "package"
      version: "v3.17.0"
    - name: "wireless_wifi"
      type: "package"
      version: "v3.12.0"
    - name: "bootloader"
      type: "package"
      version: "v3.7.0"
    - name: "cryptoauthlib"
      type: "package"
      version: "v3.7.7"
    - name: "wireless_rnbd"
      type: "package"
      version: "v2.0.4"
    - name: "wireless_system_rnwf"
      type: "package"
      version: "v3.0.0"